version: '3.7'

services:
  postgres:
    container_name: boilerplate_db
    image: bitnami/postgresql:latest
    environment:
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_DB=${TYPEORM_DATABASE}
      - PG_DATA=/var/lib/postgresql/data
    ports:
      - ${TYPEORM_PORT}:5432
    volumes:
      - postgres_data:/bitnami/postgresql
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

volumes:
  postgres_data:
